### ISSUE TITLE
Fixed Bugs?

### ISSUE THREAD

**Issue by hasanalizxc** [Virgula0/hidden-tear#2]
Dear Virgula0,

Hope you are fine. I read in readme you fixed the bugs. And i wondered did you fix the bugs (main security flaws and other encryption bugs) in this link?

https://utkusen.com/blog/destroying-the-encryption-of-hidden-tear-ransomware.html

Thanks.

**Comment by Virgula0** [comment]
Thanks for notice me of that and no... the security flaws bug is not fixed, but knowing this i'll modify it with RSA cryptography hust like EDA2 instead of using AES. However, it is for educational purpose so this could be a "backdoor" to get back datas on victim pc infected by kiddies, Not bad at all.

**Comment by hasanalizxc** [comment]
I know this project is educational purpose, i just wondered did you fix the security flaws and encryption bugs.
