### ISSUE TITLE
I don't receive the key on control panel

### ISSUE THREAD

**Issue by abstractdream** [Virgula0/hidden-tear#5]
Hello, 

When I compile, everything works fine but I don't receive the key.

I still have the message "No hacked machines found yet"

All .php are uploaded on the server and the sql database as well.

I thought the problem was from the file permission on "write.php", so I set up for "write and read" for Group and Public but I still have the same issue.

Any ideas? Thanks.

**Comment by Virgula0** [comment]
Thank you for your feedback, I will check again as soon as possible and I will update everything in case of errors.

**Comment by Virgula0** [comment]
After a long time and many issue reports, I finally decided to retest this software. Anyway, it seems still working fine, and as I thought, problems are made by misconfigurations and the inability by common users to solve them (as should be if they're looking at this project for bad intentional purposes). Just make sure you're using PHP 5.6 on your server , php 7 is not supported.

![Cattura](https://user-images.githubusercontent.com/16546435/73984075-1a82d700-4938-11ea-97b3-8e2b5de7c93b.PNG)

**Comment by Virgula0** [comment]
After a long time and many issue reports, I finally decided to retest this software. Anyway, it seems still working fine, and as I thought, problems are made by misconfigurations and the inability by common users to solve them (as should be if they're looking at this project for bad intentional purposes). Just make sure you're using PHP 5.6 on your server, PHP 7 is not supported.

![Cattura](https://user-images.githubusercontent.com/16546435/73984075-1a82d700-4938-11ea-97b3-8e2b5de7c93b.PNG)
