### ISSUE TITLE
how to configure the server to connect to the database

### ISSUE THREAD

**Issue by Mrcosta20** [Virgula0/hidden-tear#6]
Good evening friend, I am testing your project HIDDEN TEAR WITH SERVER but I have an error, I don't know if it is how you say it, bad configuration, but I get "No hacked machines found yet"
I already made all the settings that I think is fine but
I think I don't understand why there is no connection to the database
I don't understand this part that you wrote,

¿The script should write the GET parameter into a database and optionally into a text file. Sending process running in?

  It is supposed that the GET parameter is already in write.php but I don't know what else to add in your files I would like at least something explanatory of what additional settings it is necessary to make to raise the panel. and I hope I don't bother or bother you with my question thank you

**Comment by Virgula0** [comment]
I'll answer for this problem once. A lot of you asked for this problem, however, I tried again the script and it seems still working(https://github.com/Virgula0/hidden-tear/issues/5). Maybe, there is only a bug that could let the server-side not processing correctly the information sent by the client because they're not base64 encoded. The solution it's simple and I let you solve it, maybe in the next time, I'll add the fix by my hands.

You need to encode the info of the GET request with base64 encoding from the client side: https://docs.microsoft.com/en-us/dotnet/api/system.convert.tobase64string?view=netframework-4.8
Then you need to decode them in the PHP script in order to save them into the database: https://www.php.net/manual/en/function.base64-decode.php

Also, If you have tried with an attempt only, it could happen that a random generated special char brokes the saving of info by the PHP script into the database, but if you try again there are remote possibilities that this will happen again. I remember that this script is for educational purpose only and it is not maintained anymore because too old.

Try this fix it should work, otherwise, try many times by launching the ransomware client and see what happens.
